### ISSUE TITLE
测试了一下，不行

### ISSUE THREAD

**Issue by hama** [Carmenliukang/1688_crawler-image_search_products#1]
都是没有结果
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/trFQyDGK4Z1563276150568&spm=a260k.635.3262836.d1088

**Comment by Carmenliukang** [comment]
首先这个 demo 是可以直接运行的，本人对于自己的代码，是很认真的。
这是直接git clone 下来的代码。运行的结果：
1. 运行 get_1688_url_by_url.py
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/MZXwkFTh3Y1563280420423&spm=a260k.635.3262836.d1088
2. 运行 get_1688_url_by_filename.py
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/NmpTkMjdcs1563280582093&spm=a260k.635.3262836.d1088

你先看一下你的图片路径是否是正确的，这种情况很多时候都是因为你这里的 图片路径不正确。
Python 3 版本。相关依赖包都是最新版本。

**Comment by hama** [comment]
我用的2.7 。。。
运行了 get_1688_url_by_url.py  确实没结果， 必须要 3 吗？

**Comment by Carmenliukang** [comment]
我这里测试一下。看一下能不能兼容一下 Python2

**Comment by hama** [comment]
我试了一下，3 确实可以。 2.7 不行。啥问题？
python3 get_1688_url_by_url.py 
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/XpsrPmzBNA1563282675759&spm=a260k.635.3262836.d1088
4.958016872406006

python get_1688_url_by_url.py 
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/wRbAxPYsH81563282722836&spm=a260k.635.3262836.d1088
6.80216002464

**Comment by hama** [comment]
这个真牛逼了。 有测试过吗？ 频率多快会被ban掉？

**Comment by Carmenliukang** [comment]
单线程没有问题，并发如果很高，那么就会让你登入才可以看到查询的结果。你挂一个代理，然后就可以了。
Python2 为什么不行，我这里看一下 什么原因。

这个其实也不难，大概花费半天时间其实就可以了，之前使用的是 selenium 但是太不稳定了，所以才使用，也是自己太菜了，selenium 不熟悉。

**Comment by hama** [comment]
python3 完美运行！ 强大！
