### ISSUE TITLE
image API

### ISSUE THREAD

**Issue by chen-jian350** [Carmenliukang/1688_crawler-image_search_products#14]
data: {'rgv587_flag': 'sm', 'url': '/api/upload.api/_____tmd_____/punish?x5secdata=xb0392ec8244584e5e2b14e77aca3bf2a31638527762a1855144138a-1029588677abazc2ak2497771368a__bx__stream-upload.taobao.com%3A443%2Fapi%2Fupload.api&x5step=2'}  是上传图片接口更新了吗？

**Comment by Carmenliukang** [comment]
the part is developmenting

**Comment by Carmenliukang** [comment]
api v2 down
