### ISSUE TITLE
taobao image search not working 

### ISSUE THREAD

**Issue by leewoojung79** [Carmenliukang/1688_crawler-image_search_products#25]
hello~ 
When searching for Taobao images, redirected to the login page.
I tried to solve it, but it didn't work.
Is there any solution?

**Comment by Carmenliukang** [comment]
It is a little busy at the end of the year, so the problem is expected to be fixed in December.

**Comment by leewoojung79** [comment]
Still waiting for a fix.
I'm willing to pay if it can be fixed quickly.

yel11@naver.com
Please contact us.

**Comment by Carmenliukang** [comment]
The encryption algorithm of world.taobao has been updated and I need to spend more time to crack it.
I didn't have time to try it until the weekend, so it'll have to wait, but I'll fix it as soon as possible.

**Comment by Carmenliukang** [comment]
`world.taobao.com` has added login restrictions and has tried many methods but cannot solve them.

**Comment by leewoojung79** [comment]
Thank you for your help.

Can I think of it as unsolvable?

If so, we will close the issue.

**Comment by Carmenliukang** [comment]
I'm trying to add a login model to solve this problem.

**Comment by Carmenliukang** [comment]
fixed the 1688 upload bug.
