### ISSUE TITLE
image id 为0

### ISSUE THREAD

**Issue by ivanberry** [Carmenliukang/1688_crawler-image_search_products#26]
是不是可能被限制的原因呢？

{'api': 'mtop.1688.imageService.putImage', 'data': {'imageId': '0', 'requestId': 'e0c204ae6e2a451ca9e7320452c35a02', 'sessionId': '40f08ecf7c9a4d8393f75d309c537f89'}, 'ret': ['SUCCESS::调用成功'], 'v': '1.0'}
0
https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageId=0&imageIdList=0
(1688v) 

IP 更换后还是一致的问题

**Comment by Carmenliukang** [comment]
Because the app_key has been updated in the latest API.

**Comment by Carmenliukang** [comment]
Fixed
