### ISSUE TITLE
好像不行了

### ISSUE THREAD

**Issue by hama** [Carmenliukang/1688_crawler-image_search_products#3]

**Comment by hama** [comment]
现在需要加上Referer 了， Referer 为空不行。
 headers = {
        "Host": 'open-s.1688.com',
        "Cache-Control": "no-cache",
        "Referer": "https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/t56wDd43sJ1571315258000.jpg",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
    }

**Comment by Carmenliukang** [comment]
您好：
        非常感谢您的修复，现在版本已经更细。


| |
17621173188
|
|
17621173188@163.com
|
签名由网易邮箱大师定制


在2019年10月17日 20:31，fang qiang<notifications@github.com> 写道：

现在需要加上Referer 了， Referer 为空不行。
headers = {
"Host": 'open-s.1688.com',
"Cache-Control": "no-cache",
"Referer": "https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/t56wDd43sJ1571315258000.jpg",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
}
