### ISSUE TITLE
跳用get_signature方法异常

### ISSUE THREAD

**Issue by ylvsjjh** [Carmenliukang/1688_crawler-image_search_products#4]
跳用get_signature  返回403 Invalid Referer, rejecting

**Comment by Carmenliukang** [comment]
你好：
这个demo 只支持 Python3，请问你使用的是Python2还是Python3

**Comment by ylvsjjh** [comment]
你好我 是跟着你的思路 用java在实现

在 2019-10-18 18:18:49，"Carmenliukang" <notifications@github.com> 写道：


你好：
这个demo 只支持 Python3，请问你使用的是Python2还是Python3

**Comment by ylvsjjh** [comment]
你好我是跟着你的思路 用java在实现 






在 2019-10-18 18:18:49，"Carmenliukang" <notifications@github.com> 写道：


你好：
这个demo 只支持 Python3，请问你使用的是Python2还是Python3

**Comment by Carmenliukang** [comment]
403 的情况，应该就是传参的问题，麻烦将你的请求的 url params result headers 依次都发送一下。谢谢。

**Comment by ylvsjjh** [comment]
你好 我发现他的callback 参数变了 jsonp_1571393739642_9565






在 2019-10-18 18:18:49，"Carmenliukang" <notifications@github.com> 写道：


你好：
这个demo 只支持 Python3，请问你使用的是Python2还是Python3

**Comment by ylvsjjh** [comment]
1.第一步

 https://open-s.1688.com/openservice/.htm?callback=jQuery18303374729635985685_1571395343721&serviceIds=cbu.searchweb.config.system.currenttime&outfmt=jsonp&_=1571395343721 http/1.1
头部
Cache-Control: no-cache
Origin: https://www.1688.com
Accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Proxy-Connection: Keep-Alive
Host: open-s.1688.com
Connection: Keep-Alive
返回
jQuery18303374729635985685_1571395457456({"cbu.searchweb.config.system.currenttime":{"msg":"ok","dataSet":1571395551272,"time":0,"code":200}});
第二部
https://open-s.1688.com/openservice/ossDataService?appName=pc_tusou&&callback=jQuery18303536909897611926_1571395462820&appKey=cGNfdHVzb3U6MTU3MTM5NTQ2MjYzNg==&_=1571395462820 
头部
Cache-Control: no-cache
Accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Proxy-Connection: Keep-Alive
Host: open-s.1688.com
Connection: Keep-Alive
返回 
403 Invalid Referer, rejecting... 




在 2019-10-18 18:36:01，"Carmenliukang" <notifications@github.com> 写道：


403 的情况，应该就是传参的问题，麻烦将你的请求的 url params result headers 依次都发送一下。谢谢。

**Comment by Carmenliukang** [comment]
get_dataset 这个你需要模糊匹配一下，获取其中的 dataSet 这个数值 ，用于加密
可以通过这个正则 进行匹配 
"\"dataSet\":(.*?)}"

**Comment by Carmenliukang** [comment]
https://open-s.1688.com/openservice/.htm?callback=jQuery18303374729635985685_1571395343721&serviceIds=cbu.searchweb.config.system.currenttime&outfmt=jsonp&_=1571395343721 http/1.1
头部
Cache-Control: no-cache
Origin: https://www.1688.com
Accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Proxy-Connection: Keep-Alive
Host: open-s.1688.com
Connection: Keep-Alive
返回
jQuery18303374729635985685_1571395457456({"cbu.searchweb.config.system.currenttime":{"msg":"ok","dataSet":1571395551272,"time":0,"code":200}});

这里需要匹配出来 dataSet 的数值，进行加密处理

**Comment by Carmenliukang** [comment]
第二步骤这里的appKey 是需要使用第一步骤的dataSet这个进行加密。

https://open-s.1688.com/openservice/ossDataService?appName=pc_tusou&&callback=jQuery18303536909897611926_1571395462820&appKey=cGNfdHVzb3U6MTU3MTM5NTQ2MjYzNg==&_=1571395462820

**Comment by ylvsjjh** [comment]
dataSet能正常获取 并使用Base64 加密





在 2019-10-18 18:56:12，"Carmenliukang" <notifications@github.com> 写道：


第二步骤这里的appKey 是需要使用第一步骤的dataSet这个进行加密。

https://open-s.1688.com/openservice/ossDataService?appName=pc_tusou&&callback=jQuery18303536909897611926_1571395462820&appKey=cGNfdHVzb3U6MTU3MTM5NTQ2MjYzNg==&_=1571395462820

**Comment by Carmenliukang** [comment]
我看了一下，你使用的 加密的 不是 第一步骤传输的 dataSet

**Comment by Carmenliukang** [comment]
这个使用的确实是第一步骤的dataSet。请按照这个尝试一下。

**Comment by Carmenliukang** [comment]
如果没有问题了，那么就请close issue 。
