### ISSUE TITLE
淘宝

### ISSUE THREAD

**Issue by mowei199515** [Carmenliukang/1688_crawler-image_search_products#5]
伟大的博主，要是淘宝的话该怎么修改

**Comment by Carmenliukang** [comment]
This weekend will support taobao and jd pictures upload query

**Comment by ipking** [comment]
昨天还好好的
今天就不能用了
get_signature 获取不到

**Comment by Carmenliukang** [comment]
@ipking 请更新一下，已经修复了这个问题，需要增加 refer

**Comment by Carmenliukang** [comment]
@mowei199515 现在已经开始支持 淘宝和京东的以图搜货了。单独新开了一个project 
https://github.com/Carmenliukang/image_search_products.git
