### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yaooye** [Carmenliukang/1688_crawler-image_search_products#6]
<Error> <Code>MethodNotAllowed</Code> <Message>The specified method is not allowed against this resource.</Message> <RequestId>5DEDF63041381D3934690F22</RequestId> <HostId>cbusearch.oss-cn-shanghai.aliyuncs.com</HostId> <Method>POST</Method> <ResourceType>Bucket</ResourceType> </Error>

**Comment by Carmenliukang** [comment]
Hi, I have fixed this problem, please check the latest commit demo

**Comment by yaooye** [comment]
thx,已经上传成功并且生成可用搜图链接,发现您这里没有后续解析请求链接后的步骤,我自己尝试操作发现,不管换不换ip,只要不带上cookie,都是403,不知道怎么才能跳过cookie

**Comment by Carmenliukang** [comment]
你使用的1688还是淘宝？

**Comment by yaooye** [comment]
1688, 访问生成的https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/xxxxxxxxxxxxx 链接时,headers里没有cookie 就一直跳404错,有点怀疑这个链接cookie是必要参数

**Comment by Carmenliukang** [comment]
The 404 problem has been fixed, please check the latest commit

**Comment by yaooye** [comment]
抱歉,应该是我没有说清我遇到的问题,你这的demo运行没有问题,最终生成了查询url,   
 url = Alibaba().run(filename)
    print(url)

我后续对查询url进行请求,为了获取查询到的sku信息时(此为业务需求),发现只有带有登录信息的cookie才能访问到,去掉就404,切换ip也不行, 因为我看你这里demo只走到获取查询url后便结束了

**Comment by Carmenliukang** [comment]
抱歉，这部分没有考虑过。
