### ISSUE TITLE
您好，我用的是python2.7，只能使用urllib或者urllib2，然后出现了错误。

### ISSUE THREAD

**Issue by cyouho** [Carmenliukang/1688_crawler-image_search_products#8]
这个情况是因为只能用python3或者以上的版本里的 `requests.post` 么。

错误信息是:
`urllib2.HTTPError: HTTP Error 405: Method Not Allowed`

**Comment by Carmenliukang** [comment]
python 2.7 的 request.post 支持。

**Comment by cyouho** [comment]
不好意思，还有一个问题就是，没有 `header`  部分是不行的么？谢谢。

**Comment by Carmenliukang** [comment]
必须的，相关说明如下：
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers
